container:
  image: golang:latest

env:
  GOPROXY: https://gocenter.io

test_task:
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  get_script:
    - go get ./...
    - go get -u github.com/jstemmer/go-junit-report
  build_script: go build ./...
  test_script: go test -v 2>&1 | go-junit-report > reports/report.xml
  always:
    junit_result_artifacts:
      path: "reports/report.xml"
      format: junit