Tests_task:
  container:
    image: golang:latest
  env:
    GOPROXY: https://proxy.golang.org
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  get_script:
    - go get ./...
    - go get -u github.com/jstemmer/go-junit-report
  build_script: go build ./...
  test_script:
    - mkdir -p reports
    - go test -v 2>&1 | go-junit-report > reports/report.xml
  always:
    junit_result_artifacts:
      path: "reports/report.xml"
      format: junit

Lint_task:
  container:
    image: golangci/golangci-lint:latest
  script: golangci-lint run -v --out-format json > lint-report.json
  always:
    golangci_artifacts:
      path: "lint-report.json"
      type: text/json
      format: golangci