Tests_task:
  container:
    image: golang:latest
  install_script:
    - go install github.com/jstemmer/go-junit-report/v2@latest
  build_script: go build ./...
  test_script:
    - mkdir -p reports
    - go test -v ./... 2>&1 | go-junit-report > reports/report.xml
  always:
    junit_result_artifacts:
      path: "reports/report.xml"
      format: junit

task:
  name: GolangCI Lint
  container:
    image: golangci/golangci-lint:latest
  run_script: golangci-lint run -v --out-format json > lint-report.json
  always:
    golangci_artifacts:
      path: lint-report.json
      type: text/json
      format: golangci
